import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "@/components/footer"; // Ensure this path is correct
import Feature from "@/components/features"; // Ensure this path is correct
import Navbar from "@/components/header"; // Ensure this path is correct

// Load local fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff", // Ensure the font path is correct
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff", // Ensure the font path is correct
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Remove the "use client" directive for metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      publishableKey={process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY} // Ensure you have the correct public API key
    >
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar />
          {children}
          <Feature />
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
